name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # The branch where your `css_advanced` directory resides

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir -p public
          cp -r css_advanced/* public/
          echo "index.html" > public/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
